public class ContactConstants {
	public static final String LAST_NAME = 'LastName';
    public static final String FIRST_NAME= 'FirstName';
    
    public static final String HINDI = 'Hindi';
    public static final String ACCESS_DENIED = 'Hindi Teachers are not allowed to be added/modified';
    
    public static final String CONTACT = 'Contact';
    public static final String SUBJECTS = 'Subjects__c';
    public static final String Department = 'Department';
    public static final String Email = 'Email';
    
    public static final String ERROR_PARSING_DOCUMENT = 'Error Parsing Document';
}