public class OpportunityConstants {
	public static final String CLOSED_LOST = Label.Closed_Lost;
    public static final String CLOSED_WON = Label.Closed_Won;
	public static final String FOLLOW_UP_TEST_TASK = Label.Follow_Up_Test_Task;
    public static final String EXISTING = Label.EXISTING;
    public static final String INVALID_DATA = 'You must provide an Account when ' +
                    'creating Opportunities for existing Customers';
    public static final String RESET = Label.RESET;
    public static final String EMAIL_SUBJECT = 'YOur opportunity has been modified';
    public static final String UNMODIFIED_OPPORTUNITY = 'Unmodified Opporunity';
    public static final String UNMODIFIED_OPPORTUNITY_BODY = 'Your opporunity has not been modified from past 30 days';
}